services:
  app-bedrock-chat:
    container_name: app-bedrock-chat
    env_file:
      - .env.local
    build:
      context: ../app/chat
      dockerfile: ../chat/Dockerfile
      target: dev
    ports:
      - 3300:3300
    volumes:
      - ../app/chat:/app
      - app_bedrock_chat_node_modules:/chat/node_modules
    networks:
      - apps
  app_bedrock_summarization:
    container_name: app_bedrock_summarization
    env_file:
      - .env.local
    build:
      context: ../app/summarization
      dockerfile: ../summarization/Dockerfile
      target: dev
    ports:
      - 3301:3301
    volumes:
      - ../app/summarization:/app
      - app_bedrock_summarization_node_modules:/summarization/node_modules
    networks:
      - apps

networks:
  apps:
    driver: bridge

volumes:
  app_bedrock_chat_node_modules:
  app_bedrock_summarization_node_modules:
