services:
  app-bedrock-sample:
    container_name: app-bedrock-sample
    env_file:
      - .env.local
    build:
      context: ../app
      dockerfile: ../app/Dockerfile
      target: dev
    ports:
      - 3300:3300
    volumes:
      - ../app:/app
      - app_bedrock_sample_node_modules:/app/node_modules
    networks:
      - apps

networks:
  apps:
    driver: bridge

volumes:
  app_bedrock_sample_node_modules:
